### PR TITLE
Replace `document.getElementById` with `document.querySelector`

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by coliff** [comment]
hey there! thanks for the PR - but could you please explain what the benefit of changing this is?

**Comment by atefBB** [comment]
In my code (`inherited` one) the password input having an `id` attribute different then `password`, so that cause the `plugin` isn't working (I work with legacy/spaghetti code that difficult to handle and change), so I come up with a generale `selector` that works for all cases (I think). Hope my explanation make sense!

**Review by coliff — APPROVED** [review]

**Comment by coliff** [comment]
sorry for the long delay - and thanks again :-)

**Comment by coliff** [comment]
Released as part of v1.1.0
https://github.com/coliff/bootstrap-show-password-toggle/releases

**Pull request merged**
